import { NavLink, Outlet } from 'react-router-dom'
import { Activity, BarChart3, BellRing, ChevronLeft, ChevronRight, ClipboardCheck, LayoutDashboard, Search, Settings, Sparkles, Users, Menu, X } from 'lucide-react'
import { useState } from 'react'
import { useApp } from '../context/AppContext'

const nav=[
  ['Overview','/',LayoutDashboard], ['Members','/members',Users], ['Ahead Queue','/queue',BellRing],
  ['Member Intelligence','/members/M0001/intelligence',Sparkles], ['Readiness','/members/M0001/readiness',ClipboardCheck],
  ['Outreach','/members/M0001/outreach',Activity], ['Impact & Cost','/impact',BarChart3], ['Settings','/settings',Settings]
] as const

export function AppLayout(){
  const {collapsed,setCollapsed}=useApp(); const [mobile,setMobile]=useState(false)
  const sidebar=<div className="flex h-full flex-col bg-slate-950 text-slate-100"><div className="flex h-16 items-center justify-between border-b border-slate-800 px-4"><div className={`min-w-0 ${collapsed?'lg:hidden':''}`}><div className="text-sm font-bold tracking-wide">AHEAD</div><div className="text-[10px] text-slate-400">Proactive care readiness</div></div><button aria-label="Collapse sidebar" className="hidden rounded-lg p-2 hover:bg-slate-800 lg:block" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronRight size={18}/>:<ChevronLeft size={18}/>}</button><button className="rounded-lg p-2 hover:bg-slate-800 lg:hidden" onClick={()=>setMobile(false)}><X size={19}/></button></div><nav className="flex-1 space-y-1 p-2">{nav.map(([label,to,Icon])=><NavLink key={label} to={to} onClick={()=>setMobile(false)} className={({isActive})=>`flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium transition ${isActive?'bg-slate-800 text-white':'text-slate-300 hover:bg-slate-900 hover:text-white'} ${collapsed?'lg:justify-center lg:px-0':''}`} title={collapsed?label:undefined}><Icon size={18}/><span className={collapsed?'lg:hidden':''}>{label}</span></NavLink>)}</nav><div className="border-t border-slate-800 p-3"><div className={`rounded-xl bg-slate-900 p-3 ${collapsed?'lg:hidden':''}`}><p className="text-xs font-semibold text-emerald-300">Prototype Mode</p><p className="mt-1 text-[11px] leading-4 text-slate-400">Synthetic data · human approval required</p></div></div></div>
  return <div className="min-h-screen bg-panel"><aside className={`fixed inset-y-0 left-0 z-40 hidden transition-all lg:block ${collapsed?'w-16':'w-64'}`}>{sidebar}</aside>{mobile&&<div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-slate-950/40" onClick={()=>setMobile(false)}/><aside className="relative h-full w-72">{sidebar}</aside></div>}<div className={`transition-all ${collapsed?'lg:pl-16':'lg:pl-64'}`}><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-line bg-white/95 px-4 backdrop-blur sm:px-6"><div className="flex items-center gap-3"><button className="rounded-lg border border-line p-2 lg:hidden" onClick={()=>setMobile(true)}><Menu size={18}/></button><div><p className="text-sm font-semibold">Humana Ahead</p><p className="hidden text-xs text-muted sm:block">Internal Member Advocate prototype</p></div></div><div className="flex items-center gap-2 rounded-full border border-line bg-panel px-3 py-1.5 text-xs text-muted"><span className="h-2 w-2 rounded-full bg-emerald-500"/>Mock AI connected</div></header><main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8"><Outlet/></main></div></div>
}
