import { useEffect,useState } from 'react'; import { useParams } from 'react-router-dom'; import { CheckCircle2, Edit3, ShieldCheck } from 'lucide-react'; import { api } from '../services/api'
import { NotificationPreview } from '../components/NotificationPreview'
import type { OutreachDraft } from '../types/api'; import type { Member } from '../types/api'; import { PageHeader } from '../components/PageHeader'; import { MemberHeader } from '../components/MemberHeader'; import { LoadingState } from '../components/LoadingState'; import { ErrorState } from '../components/ErrorState'
export default function OutreachPage(){const {memberId}=useParams();const [member,setMember]=useState<Member>();const [draft,setDraft]=useState<OutreachDraft>();const [message,setMessage]=useState('');const [result,setResult]=useState<any>();const [err,setErr]=useState('');const [original,setOriginal]=useState('');useEffect(()=>{
    // Fail closed. Defaulting to a hardcoded member meant a missing route
    // parameter silently drafted outreach for somebody else - the wrong failure
    // mode on a screen whose entire premise is approving a message to a
    // specific member.
    if(!memberId){setErr('No member was specified. Open this screen from a member\'s readiness result.');return}
    Promise.all([api.member(memberId),api.outreachDraft(memberId)]).then(([m,d])=>{setMember(m);setDraft(d);setMessage(d.message);setOriginal(d.message)}).catch(e=>setErr(e.message))
  },[memberId]);const act=(a:'APPROVE'|'REJECT'|'SAVE_FOR_REVIEW')=>{if(!memberId)return;api.outreachAction(memberId,a,message,original).then(setResult).catch(e=>setErr(e.message))};if(err)return <ErrorState message={err}/>;if(!member||!draft)return <LoadingState label="Preparing advocate-reviewed outreach…"/>;return <><PageHeader title="Proactive Outreach" subtitle="Ahead can draft administrative outreach, but a Member Advocate remains the decision-maker. Prototype Mode never sends a real message."/><MemberHeader member={member}/><div className="grid gap-5 xl:grid-cols-3"><section className="card xl:col-span-2"><div className="flex items-start justify-between"><div><p className="eyebrow">Generated outreach draft</p><h2 className="section-title mt-1">Edit before approval</h2></div><Edit3 className="text-brand" size={20}/></div><textarea className="mt-4 min-h-48 w-full rounded-xl border border-line p-4 text-base leading-7" value={message} onChange={e=>setMessage(e.target.value)}/><p className="mt-2 text-xs text-muted">Channel preference: {draft.channel}. Message class: <span className="font-semibold">{String(draft.message_class||'INFORMATIONAL').replaceAll('_',' ').toLowerCase()}</span>. {message.trim()!==original.trim() && <span className="font-semibold text-amber-800">Edited — the change is recorded.</span>}</p>
      {draft.checklist&&draft.checklist.length>0&&<div className="mt-5"><NotificationPreview headline={draft.headline||''} message={message} event={draft.predicted_care_event||''} score={draft.readiness_score||0} label={draft.readiness_label||''} checklist={draft.checklist} readyCount={draft.ready_count||0} totalItems={draft.total_items||0} channel={draft.channel} resolutionMode={draft.resolution_mode||'NO_ACTION'} callToAction={draft.call_to_action||''} options={draft.member_options||[]} advocateRequired={!!draft.advocate_required}/></div>}
      <p className="mt-1 text-xs text-muted">Governance is applied per message class, not per confidence level. Every class currently requires advocate approval; automation is earned per class from override data.</p></section><aside className="card"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-brand" size={20}/><div><p className="font-semibold">Human approval required</p><p className="mt-1 text-sm leading-6 text-muted">AI can draft and prioritize. It cannot autonomously contact this synthetic member.</p></div></div><div className="mt-5 space-y-2"><button className="btn-primary w-full" onClick={()=>act('APPROVE')}>Approve & Send</button><button className="btn-secondary w-full" onClick={()=>act('SAVE_FOR_REVIEW')}>Save for Review</button><button className="btn-secondary w-full text-rose-700" onClick={()=>act('REJECT')}>Do Not Contact</button></div></aside></div>{result&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 text-emerald-700"/><div><p className="font-semibold text-emerald-800">{result.status.replaceAll('_',' ')}</p><p className="mt-1 text-sm text-emerald-700">{result.message}</p></div></div></div>}</>}
