import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Activity, BrainCircuit, CircleDollarSign, ClipboardCheck, Users } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../services/api'
import { PageHeader } from '../components/PageHeader'
import { MetricCard } from '../components/MetricCard'
import { LoadingState } from '../components/LoadingState'
import { ErrorState } from '../components/ErrorState'

export default function OverviewPage(){
  const [data,setData]=useState<any>();const [err,setErr]=useState('');const nav=useNavigate()
  useEffect(()=>{api.overview().then(setData).catch(e=>setErr(e.message))},[])
  if(err)return <ErrorState message={err}/>;if(!data)return <LoadingState label="Loading Ahead overview…"/>
  const k=data.kpis
  return <><PageHeader title="Overview" subtitle="A cost-aware funnel: browsing data is free; Agent 1 and Agent 2 run only after explicit advocate actions." action={<button className="btn-primary" onClick={()=>nav('/members')}>Start member assessment</button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Active members" value={k.active_members} detail="Synthetic MA population" Icon={Users}/><MetricCard label="Meaningful recent activity" value={k.meaningful_activity} detail="Deterministic Tier 0 signal" Icon={Activity}/><MetricCard label="Members actually scanned" value={k.members_evaluated} detail="Explicit Agent 1 calls" Icon={BrainCircuit}/><MetricCard label="High-confidence care intent" value={k.high_confidence_care_intent} detail="Eligible for Agent 2"/><MetricCard label="Readiness assessments" value={k.readiness_assessments} detail="Explicit Agent 2 calls" Icon={ClipboardCheck}/><MetricCard label="Estimated session AI cost" value={`$${Number(k.estimated_ai_cost).toFixed(4)}`} detail="Based on API token usage" Icon={CircleDollarSign}/></div><div className="mt-6 grid gap-6 xl:grid-cols-5"><section className="card xl:col-span-3"><p className="eyebrow">Compute funnel</p><h2 className="section-title mt-1">Deep reasoning only after an explicit selection</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.funnel} layout="vertical" margin={{left:10,right:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:12}}/><YAxis type="category" dataKey="label" width={155} tick={{fontSize:12}}/><Tooltip/><Bar dataKey="value" fill="#5C8727" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></div></section><section className="card xl:col-span-2"><p className="eyebrow">Recent explicit scans</p><h2 className="section-title mt-1">Nothing is generated until you click Scan</h2>{data.recent_assessments.length===0?<div className="mt-5 rounded-lg bg-panel p-5 text-sm leading-6 text-muted">No Agent 1 assessments have been run yet. Go to Members, select one or more members and click <strong>Scan for upcoming procedures</strong>.</div>:<div className="mt-4 divide-y divide-line">{data.recent_assessments.map((a:any)=><button key={a.member_id} onClick={()=>nav(`/members/${a.member_id}/intelligence`)} className="w-full py-4 text-left hover:bg-panel"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">{a.member_id}</p><p className="mt-1 text-sm text-muted">{a.event}</p><p className="mt-1 text-xs text-muted">Contact risk: {a.contact_risk}</p></div><div className="text-right"><p className="text-sm font-semibold text-brand">{Math.round(a.confidence*100)}%</p><p className="text-xs text-muted">Care intent</p>{a.readiness!=null&&<p className="mt-2 text-xs font-medium">{a.readiness}% ready</p>}</div></div></button>)}</div>}</section></div></>
}
