"""Agent 2 - Administrative Readiness.

Every factual status and the score itself are computed deterministically in
Python. The model receives the finished checklist and does exactly two things:
choose which unresolved item to surface first, and write one advocate-facing
sentence. Its choice is validated against the real checklist and discarded if it
names an invalid or already-resolved key.

Score weights encode two things: the member cost exposure an unresolved item
creates, and the effort required to resolve it. Out-of-network carries the
largest deduction because it has the largest financial consequence for the
member and the longest lead time to fix. They are a v1 heuristic, configurable,
and would be re-derived from actual advocate resolution times in a pilot.
"""

import hashlib
import json
import re
import time
from sqlalchemy.orm import Session
from app import models
from app.config import settings
from app.schemas import CareIntentResult, ReadinessItem, ReadinessResult, ProviderAlternative
from app.services import result_store
from app.services.settings_service import get_runtime_settings
from app.services.usage import estimate_tokens, log_usage
from app.agents.openai_provider import OpenAIProvider

SERVICE_MAP = {
    "Total knee replacement": ("KNEE_ARTHROPLASTY", "Orthopedic Surgery"),
    "Total hip replacement": ("HIP_ARTHROPLASTY", "Orthopedic Surgery"),
    "Cataract surgery": ("CATARACT_SURGERY", "Ophthalmology"),
}

# Documented weights, surfaced to the UI so an advocate can see what drives a
# score rather than being handed an unexplained number.
SCORE_WEIGHTS = {
    "coverage_not_covered": 25,
    "coverage_unknown": 10,
    "network_out_of_network": 30,
    "network_unknown": 8,
    "authorization_missing": 25,
    "authorization_in_progress": 10,
    "authorization_unknown": 8,
    "referral_conditional": 5,
    "cost_unknown": 10,
}

WEIGHT_RATIONALE = (
    "Deductions reflect member cost exposure and advocate effort to resolve. "
    "Out-of-network carries the largest weight because it has the greatest "
    "financial consequence for the member and the longest lead time to correct. "
    "These are a configurable v1 heuristic, not an empirically derived model."
)

READINESS_AGENT_PROMPT = """You are Agent 2, the Administrative Readiness Agent for a payer Member Advocate application.
The application has already performed deterministic lookups for plan coverage, provider/facility network, prior authorization, referral rules, member cost-share context, and relevant supplemental benefits.

You MUST NOT change, invent, or reinterpret the factual checklist statuses or readiness score. Your job is only to prioritize the unresolved administrative issue and propose a concise next administrative action for a Member Advocate.

Do not provide clinical advice, diagnosis, treatment recommendations, or guarantees of coverage. If every relevant item is READY or NOT_APPLICABLE, say that no major administrative action is identified and recommend monitoring/confirming final details.

Return exactly one JSON object:
{
  "top_issue_key": "one checklist key" or null,
  "recommended_next_action": "one concise, actionable administrative sentence"
}
Never reveal chain-of-thought."""


MIN_NAME_LENGTH = 5


def _mentions(name: str | None, text: str) -> bool:
    """Word-boundary match.

    A raw substring test matched a provider called Lee inside the word believe,
    and Park inside parking. Because this resolution drives network status, and
    network status carries the largest deduction in the scoring system, a false
    match could move a member from ninety-five per cent to forty. Word
    boundaries plus a length floor remove that class of error.
    """
    if not name or len(name.strip()) < MIN_NAME_LENGTH:
        return False
    return re.search(rf"\b{re.escape(name.strip().lower())}\b", text) is not None


def _find_likely_provider_ids(db: Session, member_id: str, specialty: str,
                              ) -> tuple[str | None, str | None, list[str]]:
    """Resolve the likely provider and facility from administrative records only.

    Structured sources are consulted FIRST - authorization records, then claims -
    because they are reliable. Free-text mention in a call summary is the last
    resort, and is word-boundary matched. No provider name is ever generated by
    the model. The third return value records which source won, so the UI can
    show how a provider was identified.
    """
    practitioner_id: str | None = None
    facility_id: str | None = None
    provenance: list[str] = []

    # 1. Prior authorizations - the most reliable administrative signal.
    pas = (db.query(models.PriorAuthorization)
           .filter(models.PriorAuthorization.member_id == member_id)
           .order_by(models.PriorAuthorization.request_date.desc()).all())
    for pa in pas:
        provider = db.get(models.ProviderDirectory, pa.requesting_provider_id) if pa.requesting_provider_id else None
        if not practitioner_id and provider and provider.specialty == specialty:
            practitioner_id = provider.provider_id
            provenance.append("surgeon resolved from authorization record")
        if not facility_id and pa.facility_id:
            facility_id = pa.facility_id
            provenance.append("facility resolved from authorization record")
        if practitioner_id and facility_id:
            return practitioner_id, facility_id, provenance

    # 2. Adjudicated claims.
    claims = (db.query(models.ClaimHistory)
              .filter(models.ClaimHistory.member_id == member_id)
              .order_by(models.ClaimHistory.service_from_date.desc()).all())
    for claim in claims:
        provider = db.get(models.ProviderDirectory, claim.provider_id) if claim.provider_id else None
        if not practitioner_id and provider and provider.specialty == specialty:
            practitioner_id = provider.provider_id
            provenance.append("surgeon resolved from recent claim")
        if not facility_id and claim.facility_id:
            claim_facility = db.get(models.ProviderDirectory, claim.facility_id)
            if claim_facility and claim_facility.provider_type == "FACILITY":
                facility_id = claim_facility.provider_id
                provenance.append("facility resolved from recent claim")
        if practitioner_id and facility_id:
            return practitioner_id, facility_id, provenance

    # 3. Free text, last resort, word-boundary matched.
    if not practitioner_id or not facility_id:
        summaries = (db.query(models.AgentAssistSummary)
                     .filter(models.AgentAssistSummary.member_id == member_id)
                     .order_by(models.AgentAssistSummary.call_start_timestamp.desc())
                     .limit(6).all())
        text = " ".join(((s.summary_text or "") + " " + (s.follow_up_note or ""))
                        for s in summaries).lower()
        if not practitioner_id:
            for provider in db.query(models.ProviderDirectory).filter(
                models.ProviderDirectory.provider_type == "PRACTITIONER",
                models.ProviderDirectory.specialty == specialty,
            ).all():
                if _mentions(provider.provider_name, text):
                    practitioner_id = provider.provider_id
                    provenance.append("surgeon named in a recent call summary")
                    break
        if not facility_id:
            for facility in db.query(models.ProviderDirectory).filter(
                models.ProviderDirectory.provider_type == "FACILITY"
            ).all():
                if _mentions(facility.provider_name, text) or _mentions(facility.organization_name, text):
                    facility_id = facility.provider_id
                    provenance.append("facility named in a recent call summary")
                    break

    return practitioner_id, facility_id, provenance


def _network_status(db: Session, plan_id: str, provider_id: str | None):
    if not provider_id:
        return None
    return db.query(models.ProviderNetwork).filter(
        models.ProviderNetwork.plan_id == plan_id,
        models.ProviderNetwork.provider_id == provider_id,
    ).first()


def get_alternatives(db: Session, member_id: str, specialty: str, provider_type: str | None = None, limit: int = 3) -> list[ProviderAlternative]:
    member = db.get(models.MemberEnrollment, member_id)
    if not member:
        return []
    q = db.query(models.ProviderDirectory).join(
        models.ProviderNetwork, models.ProviderNetwork.provider_id == models.ProviderDirectory.provider_id
    ).filter(
        models.ProviderNetwork.plan_id == member.plan_id,
        models.ProviderNetwork.network_status == "IN_NETWORK",
        models.ProviderDirectory.accepting_new_patients.is_(True),
    )
    if provider_type:
        q = q.filter(models.ProviderDirectory.provider_type == provider_type)
    if specialty:
        q = q.filter(models.ProviderDirectory.specialty == specialty)
    providers = q.all()
    providers.sort(key=lambda p: (0 if p.zip3 == member.zip3 else 1, p.city, p.provider_name))
    return [ProviderAlternative(
        provider_id=p.provider_id,
        provider_name=p.provider_name,
        organization_name=p.organization_name,
        specialty=p.specialty,
        city=p.city,
        state=p.state,
        zip3=p.zip3,
        network_status="IN_NETWORK",
        accepting_new_patients=p.accepting_new_patients,
    ) for p in providers[:limit]]


def get_latest_readiness(db: Session, member_id: str) -> ReadinessResult | None:
    return result_store.get_latest_readiness(db, member_id)


def get_all_latest_readiness(db: Session) -> dict[str, ReadinessResult]:
    return result_store.all_latest_readiness(db)


def _build_deterministic_readiness(db: Session, member_id: str, care: CareIntentResult) -> tuple[ReadinessResult, str]:
    runtime = get_runtime_settings(db)
    if care.care_intent.confidence < runtime["care_intent_threshold"] or not care.care_intent.detected:
        raise ValueError("CARE_INTENT_BELOW_THRESHOLD")

    event = care.care_intent.predicted_care_event or "Unknown care event"
    if event not in SERVICE_MAP:
        # Fail loudly rather than degrading quietly. Falling through to a generic
        # service group produced a checklist full of UNKNOWN statuses and
        # deductions that had nothing to do with the member. Agent 1 will predict
        # any procedure; the readiness layer is deliberately scoped to procedure
        # families that have a benefit-group mapping, which is configuration.
        raise ValueError("SERVICE_GROUP_UNSUPPORTED")
    service_group, specialty = SERVICE_MAP[event]
    member = db.get(models.MemberEnrollment, member_id)
    if not member:
        raise ValueError("MEMBER_NOT_FOUND")

    benefit = db.query(models.PlanBenefit).filter(
        models.PlanBenefit.plan_id == member.plan_id,
        models.PlanBenefit.service_group == service_group,
    ).first()
    accumulator = db.get(models.BenefitAccumulator, member_id)
    surgeon_id, facility_id, provenance = _find_likely_provider_ids(db, member_id, specialty)
    surgeon_network = _network_status(db, member.plan_id, surgeon_id)
    facility_network = _network_status(db, member.plan_id, facility_id)
    pa = db.query(models.PriorAuthorization).filter(
        models.PriorAuthorization.member_id == member_id,
        models.PriorAuthorization.service_group == service_group,
    ).order_by(models.PriorAuthorization.request_date.desc()).first()

    items: list[ReadinessItem] = []
    score = 100
    explanations: list[str] = []

    def add(key: str, label: str, status: str, detail: str, deduction: int = 0):
        nonlocal score
        score -= deduction
        if deduction:
            explanations.append(f"-{deduction} {label}: {detail}")
        items.append(ReadinessItem(key=key, label=label, status=status, detail=detail, deduction=deduction))

    if benefit and benefit.coverage_status == "COVERED":
        add("coverage", "Predicted procedure coverage", "READY", f"{benefit.benefit_name} is covered under the synthetic plan configuration.")
    elif benefit:
        add("coverage", "Predicted procedure coverage", "NEEDS_ATTENTION", f"Plan configuration shows {benefit.coverage_status}.", SCORE_WEIGHTS["coverage_not_covered"])
    else:
        add("coverage", "Predicted procedure coverage", "UNKNOWN", "No matching plan-benefit row was found.", SCORE_WEIGHTS["coverage_unknown"])

    if surgeon_network:
        st = surgeon_network.network_status
        status = "READY" if st == "IN_NETWORK" else "NEEDS_ATTENTION" if st == "OUT_OF_NETWORK" else "UNKNOWN"
        deduction = (SCORE_WEIGHTS["network_out_of_network"] if st == "OUT_OF_NETWORK"
                     else SCORE_WEIGHTS["network_unknown"] if st not in {"IN_NETWORK", "OUT_OF_NETWORK"} else 0)
        source = next((p for p in provenance if p.startswith("surgeon")), "resolved from administrative records")
        add("surgeon_network", "Surgeon / provider network", status,
            f"Network status: {st}; last verified {surgeon_network.last_verified_date}. Provider {source}.", deduction)
    else:
        add("surgeon_network", "Surgeon / provider network", "UNKNOWN",
            "The likely surgeon/provider could not be resolved from authorization records, recent claims or call summaries.",
            SCORE_WEIGHTS["network_unknown"])

    if facility_network:
        st = facility_network.network_status
        status = "READY" if st == "IN_NETWORK" else "NEEDS_ATTENTION" if st == "OUT_OF_NETWORK" else "UNKNOWN"
        deduction = (SCORE_WEIGHTS["network_out_of_network"] if st == "OUT_OF_NETWORK"
                     else SCORE_WEIGHTS["network_unknown"] if st not in {"IN_NETWORK", "OUT_OF_NETWORK"} else 0)
        source = next((p for p in provenance if p.startswith("facility")), "resolved from administrative records")
        add("facility_network", "Facility network", status,
            f"Network status: {st}; last verified {facility_network.last_verified_date}. Facility {source}.", deduction)
    else:
        add("facility_network", "Facility network", "UNKNOWN",
            "The likely facility could not be resolved from authorization records, recent claims or call summaries.",
            SCORE_WEIGHTS["network_unknown"])

    pa_rule = benefit.prior_authorization_rule if benefit else "CONDITIONAL"
    if pa_rule == "NOT_REQUIRED":
        add("authorization", "Prior authorization", "NOT_APPLICABLE", "The synthetic benefit configuration marks prior authorization as not required for this service group.")
    elif pa:
        mapping = {
            "APPROVED": "READY",
            "PENDING": "IN_PROGRESS",
            "MORE_INFORMATION_REQUIRED": "NEEDS_ATTENTION",
            "DENIED": "NEEDS_ATTENTION",
            "CANCELLED": "UNKNOWN",
        }
        status = mapping.get(pa.authorization_status, "UNKNOWN")
        deduction = (0 if status == "READY"
                     else SCORE_WEIGHTS["authorization_in_progress"] if status == "IN_PROGRESS"
                     else SCORE_WEIGHTS["authorization_missing"] if status == "NEEDS_ATTENTION"
                     else SCORE_WEIGHTS["authorization_unknown"])
        add("authorization", "Prior authorization", status, f"Authorization status: {pa.authorization_status}.", deduction)
    else:
        add("authorization", "Prior authorization", "NEEDS_ATTENTION", "No matching authorization record was found for a service with a conditional authorization rule.", SCORE_WEIGHTS["authorization_missing"])

    referral_rule = benefit.referral_rule if benefit else "CONDITIONAL"
    add(
        "referral",
        "Referral",
        "NOT_APPLICABLE" if referral_rule == "NOT_REQUIRED" else "UNKNOWN",
        "Referral is not required by this synthetic benefit configuration."
        if referral_rule == "NOT_REQUIRED"
        else "Referral requirement is conditional and should be confirmed with the provider workflow.",
        0 if referral_rule == "NOT_REQUIRED" else SCORE_WEIGHTS["referral_conditional"],
    )

    if accumulator:
        add(
            "cost",
            "Member cost-share context",
            "READY",
            f"${accumulator.medical_deductible_remaining:,.0f} deductible and ${accumulator.in_network_oop_remaining:,.0f} in-network OOP remaining in the synthetic accumulator.",
        )
    else:
        add("cost", "Member cost-share context", "UNKNOWN", "Benefit accumulator is unavailable.", SCORE_WEIGHTS["cost_unknown"])

    # These are benefit availability checks only. Absence of a utilization/arrangement record is not treated as a problem.
    for group, key, label in [
        ("PHYSICAL_THERAPY", "pt", "Physical therapy benefit"),
        ("TRANSPORTATION", "transportation", "Transportation benefit"),
        ("DME", "dme", "DME benefit"),
        ("HOME_HEALTH", "home_health", "Home health benefit"),
    ]:
        b = db.query(models.PlanBenefit).filter(
            models.PlanBenefit.plan_id == member.plan_id,
            models.PlanBenefit.service_group == group,
        ).first()
        if not b:
            add(key, label, "UNKNOWN", "No matching benefit row is available.")
        elif b.coverage_status == "COVERED":
            add(key, label, "READY", f"Covered: {b.coverage_limit_or_note}; member cost share {b.in_network_member_cost_share}.")
        else:
            add(key, label, "NOT_APPLICABLE", "This benefit is not included in the synthetic plan configuration.")

    score = max(0, min(100, score))
    unresolved = [i for i in items if i.status in {"NEEDS_ATTENTION", "IN_PROGRESS", "UNKNOWN"}]
    deterministic_top = unresolved[0] if unresolved else None

    alternatives: list[ProviderAlternative] = []
    if any(i.key == "facility_network" and i.status == "NEEDS_ATTENTION" for i in items):
        alternatives = get_alternatives(db, member_id, "Hospital / Surgical Facility", provider_type="FACILITY")
    elif any(i.key == "surgeon_network" and i.status == "NEEDS_ATTENTION" for i in items):
        alternatives = get_alternatives(db, member_id, specialty, provider_type="PRACTITIONER")

    label = "Administratively ready" if score >= 85 else "Mostly ready" if score >= 70 else "Needs attention"
    baseline = ReadinessResult(
        member_id=member_id,
        predicted_care_event=event,
        readiness_score=score,
        readiness_label=label,
        checklist=items,
        top_issue=deterministic_top.label if deterministic_top else None,
        score_explanation=explanations,
        alternatives=alternatives,
        recommended_next_action="Continue monitoring and confirm final administrative details." if not deterministic_top else f"Resolve or verify {deterministic_top.label.lower()}.",
        generated_by="Deterministic readiness checks",
        weight_rationale=WEIGHT_RATIONALE,
        provider_provenance=provenance,
    )
    return baseline, specialty


READINESS_AGENT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["top_issue_key", "recommended_next_action"],
    "properties": {
        "top_issue_key": {"type": ["string", "null"]},
        "recommended_next_action": {"type": "string"},
    },
}


def _readiness_cache_key(member_id: str, event: str) -> str:
    """Keyed on member, procedure and model only.

    Confidence was previously part of the key, so 0.84 and 0.8401 were different
    cache entries and produced a duplicate paid call for identical facts. The
    readiness output does not depend on confidence at all - it depends on the
    deterministic checklist.
    """
    raw = json.dumps({"m": member_id, "e": event, "model": settings.openai_model,
                      "pv": settings.prompt_version}, sort_keys=True)
    return hashlib.sha256(raw.encode()).hexdigest()[:32]


async def analyze_readiness(db: Session, member_id: str, care: CareIntentResult) -> ReadinessResult:
    if settings.use_mock_ai:
        raise RuntimeError("Mock AI is disabled for this version. Configure OPENAI_API_KEY.")

    event = care.care_intent.predicted_care_event or ""
    cache_key = _readiness_cache_key(member_id, event)
    cached = result_store.get_readiness_by_key(db, cache_key)
    if cached:
        return cached

    baseline, _ = _build_deterministic_readiness(db, member_id, care)
    packet = {
        "member_id": member_id,
        "predicted_care_event": baseline.predicted_care_event,
        "care_intent_confidence": care.care_intent.confidence,
        "readiness_score": baseline.readiness_score,
        "checklist": [item.model_dump() for item in baseline.checklist],
        "available_in_network_alternatives": [alt.model_dump() for alt in baseline.alternatives],
    }

    started = time.perf_counter()
    provider = OpenAIProvider()
    agent_output, usage = await provider.generate_json(
        system_prompt=READINESS_AGENT_PROMPT, user_payload=packet,
        schema=READINESS_AGENT_SCHEMA, schema_name="readiness_priority",
    )

    # The model's choice is validated against the real checklist. If it names a
    # key that does not exist, or one already resolved, it is discarded in favour
    # of the deterministic ordering. The model never changes a fact or a score.
    valid_keys = {item.key: item for item in baseline.checklist}
    requested_key = agent_output.get("top_issue_key")
    if requested_key not in valid_keys or valid_keys[requested_key].status not in {
        "NEEDS_ATTENTION", "IN_PROGRESS", "UNKNOWN"
    }:
        unresolved = [i for i in baseline.checklist
                      if i.status in {"NEEDS_ATTENTION", "IN_PROGRESS", "UNKNOWN"}]
        requested_key = unresolved[0].key if unresolved else None

    top_issue = valid_keys[requested_key].label if requested_key else None
    action = str(agent_output.get("recommended_next_action") or baseline.recommended_next_action).strip()
    if not action:
        action = baseline.recommended_next_action

    result = baseline.model_copy(update={
        "top_issue": top_issue,
        "recommended_next_action": action,
        "generated_by": f"OPENAI · {settings.openai_model} + deterministic checks",
    })

    latency = int((time.perf_counter() - started) * 1000)
    input_tokens = usage.get("input_tokens") or estimate_tokens(json.dumps(packet, default=str))
    output_tokens = usage.get("output_tokens") or estimate_tokens(json.dumps(agent_output))
    log_usage(
        db, agent_name="READINESS", member_id=member_id,
        input_tokens=input_tokens, output_tokens=output_tokens, latency_ms=latency,
        transcript_tool_invoked=False, mode=f"OPENAI:{settings.openai_model}",
        correlation_id=usage.get("correlation_id", ""),
        prompt_version=settings.prompt_version,
        token_source="API" if usage.get("input_tokens") else "ESTIMATED",
    )
    result_store.save_readiness(db, cache_key=cache_key, member_id=member_id,
                                result=result, model=settings.openai_model)
    return result
