import json
import time
from sqlalchemy.orm import Session
from app import models
from app.config import settings
from app.schemas import CareIntentResult, ReadinessItem, ReadinessResult, ProviderAlternative
from app.services.settings_service import get_runtime_settings
from app.services.usage import estimate_tokens, log_usage
from app.agents.openai_provider import OpenAIProvider

READINESS_CACHE: dict[tuple[str, str, float, str], ReadinessResult] = {}
LATEST_READINESS_RESULTS: dict[str, ReadinessResult] = {}

SERVICE_MAP = {
    "Total knee replacement": ("KNEE_ARTHROPLASTY", "Orthopedic Surgery"),
    "Total hip replacement": ("HIP_ARTHROPLASTY", "Orthopedic Surgery"),
    "Cataract surgery": ("CATARACT_SURGERY", "Ophthalmology"),
}

READINESS_AGENT_PROMPT = """You are Agent 2, the Administrative Readiness Agent for a payer Member Advocate application.
The application has already performed deterministic lookups for plan coverage, provider/facility network, prior authorization, referral rules, member cost-share context, and relevant supplemental benefits.

You MUST NOT change, invent, or reinterpret the factual checklist statuses or readiness score. Your job is only to prioritize the unresolved administrative issue and propose a concise next administrative action for a Member Advocate.

Do not provide clinical advice, diagnosis, treatment recommendations, or guarantees of coverage. If every relevant item is READY or NOT_APPLICABLE, say that no major administrative action is identified and recommend monitoring/confirming final details.

Return exactly one JSON object:
{
  "top_issue_key": "one checklist key" or null,
  "recommended_next_action": "one concise, actionable administrative sentence"
}
Never reveal chain-of-thought."""


def _find_likely_provider_ids(db: Session, member_id: str, specialty: str) -> tuple[str | None, str | None]:
    """Resolve likely provider/facility only from data already present after Agent 1's gate.

    Prefer names explicitly mentioned in recent Agent Assist summaries, then matching PA records,
    then recent claims. No provider names are generated by the model.
    """
    summaries = (
        db.query(models.AgentAssistSummary)
        .filter(models.AgentAssistSummary.member_id == member_id)
        .order_by(models.AgentAssistSummary.call_start_timestamp.desc())
        .limit(6)
        .all()
    )
    text = " ".join((s.summary_text or "") + " " + (s.follow_up_note or "") for s in summaries).lower()

    practitioner_id = None
    facility_id = None
    practitioners = db.query(models.ProviderDirectory).filter(
        models.ProviderDirectory.provider_type == "PRACTITIONER",
        models.ProviderDirectory.specialty == specialty,
    ).all()
    for provider in practitioners:
        if provider.provider_name and provider.provider_name.lower() in text:
            practitioner_id = provider.provider_id
            break

    facilities = db.query(models.ProviderDirectory).filter(models.ProviderDirectory.provider_type == "FACILITY").all()
    for facility in facilities:
        candidates = [facility.provider_name, facility.organization_name]
        if any(name and name.lower() in text for name in candidates):
            facility_id = facility.provider_id
            break

    pas = (
        db.query(models.PriorAuthorization)
        .filter(models.PriorAuthorization.member_id == member_id)
        .order_by(models.PriorAuthorization.request_date.desc())
        .all()
    )
    for pa in pas:
        provider = db.get(models.ProviderDirectory, pa.requesting_provider_id) if pa.requesting_provider_id else None
        if not practitioner_id and provider and provider.specialty == specialty:
            practitioner_id = provider.provider_id
        if not facility_id and pa.facility_id:
            facility_id = pa.facility_id
        if practitioner_id and facility_id:
            return practitioner_id, facility_id

    claims = (
        db.query(models.ClaimHistory)
        .filter(models.ClaimHistory.member_id == member_id)
        .order_by(models.ClaimHistory.service_from_date.desc())
        .all()
    )
    for claim in claims:
        provider = db.get(models.ProviderDirectory, claim.provider_id) if claim.provider_id else None
        if not practitioner_id and provider and provider.specialty == specialty:
            practitioner_id = provider.provider_id
        if not facility_id and claim.facility_id:
            claim_facility = db.get(models.ProviderDirectory, claim.facility_id)
            if claim_facility and claim_facility.provider_type == "FACILITY":
                facility_id = claim_facility.provider_id
        if practitioner_id and facility_id:
            break
    return practitioner_id, facility_id


def _network_status(db: Session, plan_id: str, provider_id: str | None):
    if not provider_id:
        return None
    return db.query(models.ProviderNetwork).filter(
        models.ProviderNetwork.plan_id == plan_id,
        models.ProviderNetwork.provider_id == provider_id,
    ).first()


def get_alternatives(db: Session, member_id: str, specialty: str, provider_type: str | None = None, limit: int = 3) -> list[ProviderAlternative]:
    member = db.get(models.MemberEnrollment, member_id)
    if not member:
        return []
    q = db.query(models.ProviderDirectory).join(
        models.ProviderNetwork, models.ProviderNetwork.provider_id == models.ProviderDirectory.provider_id
    ).filter(
        models.ProviderNetwork.plan_id == member.plan_id,
        models.ProviderNetwork.network_status == "IN_NETWORK",
        models.ProviderDirectory.accepting_new_patients.is_(True),
    )
    if provider_type:
        q = q.filter(models.ProviderDirectory.provider_type == provider_type)
    if specialty:
        q = q.filter(models.ProviderDirectory.specialty == specialty)
    providers = q.all()
    providers.sort(key=lambda p: (0 if p.zip3 == member.zip3 else 1, p.city, p.provider_name))
    return [ProviderAlternative(
        provider_id=p.provider_id,
        provider_name=p.provider_name,
        organization_name=p.organization_name,
        specialty=p.specialty,
        city=p.city,
        state=p.state,
        zip3=p.zip3,
        network_status="IN_NETWORK",
        accepting_new_patients=p.accepting_new_patients,
    ) for p in providers[:limit]]


def get_latest_readiness(member_id: str) -> ReadinessResult | None:
    return LATEST_READINESS_RESULTS.get(member_id)


def get_all_latest_readiness() -> dict[str, ReadinessResult]:
    return dict(LATEST_READINESS_RESULTS)


def _build_deterministic_readiness(db: Session, member_id: str, care: CareIntentResult) -> tuple[ReadinessResult, str]:
    runtime = get_runtime_settings(db)
    if care.care_intent.confidence < runtime["care_intent_threshold"] or not care.care_intent.detected:
        raise ValueError("CARE_INTENT_BELOW_THRESHOLD")

    event = care.care_intent.predicted_care_event or "Unknown care event"
    service_group, specialty = SERVICE_MAP.get(event, ("OUTPATIENT_SURGERY", care.care_intent.care_category or ""))
    member = db.get(models.MemberEnrollment, member_id)
    if not member:
        raise ValueError("MEMBER_NOT_FOUND")

    benefit = db.query(models.PlanBenefit).filter(
        models.PlanBenefit.plan_id == member.plan_id,
        models.PlanBenefit.service_group == service_group,
    ).first()
    accumulator = db.get(models.BenefitAccumulator, member_id)
    surgeon_id, facility_id = _find_likely_provider_ids(db, member_id, specialty)
    surgeon_network = _network_status(db, member.plan_id, surgeon_id)
    facility_network = _network_status(db, member.plan_id, facility_id)
    pa = db.query(models.PriorAuthorization).filter(
        models.PriorAuthorization.member_id == member_id,
        models.PriorAuthorization.service_group == service_group,
    ).order_by(models.PriorAuthorization.request_date.desc()).first()

    items: list[ReadinessItem] = []
    score = 100
    explanations: list[str] = []

    def add(key: str, label: str, status: str, detail: str, deduction: int = 0):
        nonlocal score
        score -= deduction
        if deduction:
            explanations.append(f"-{deduction} {label}: {detail}")
        items.append(ReadinessItem(key=key, label=label, status=status, detail=detail, deduction=deduction))

    if benefit and benefit.coverage_status == "COVERED":
        add("coverage", "Predicted procedure coverage", "READY", f"{benefit.benefit_name} is covered under the synthetic plan configuration.")
    elif benefit:
        add("coverage", "Predicted procedure coverage", "NEEDS_ATTENTION", f"Plan configuration shows {benefit.coverage_status}.", 25)
    else:
        add("coverage", "Predicted procedure coverage", "UNKNOWN", "No matching plan-benefit row was found.", 10)

    if surgeon_network:
        st = surgeon_network.network_status
        status = "READY" if st == "IN_NETWORK" else "NEEDS_ATTENTION" if st == "OUT_OF_NETWORK" else "UNKNOWN"
        deduction = 30 if st == "OUT_OF_NETWORK" else 8 if st not in {"IN_NETWORK", "OUT_OF_NETWORK"} else 0
        add("surgeon_network", "Surgeon / provider network", status, f"Network status: {st}; last verified {surgeon_network.last_verified_date}.", deduction)
    else:
        add("surgeon_network", "Surgeon / provider network", "UNKNOWN", "The likely surgeon/provider could not be resolved from recent administrative evidence.", 8)

    if facility_network:
        st = facility_network.network_status
        status = "READY" if st == "IN_NETWORK" else "NEEDS_ATTENTION" if st == "OUT_OF_NETWORK" else "UNKNOWN"
        deduction = 30 if st == "OUT_OF_NETWORK" else 8 if st not in {"IN_NETWORK", "OUT_OF_NETWORK"} else 0
        add("facility_network", "Facility network", status, f"Network status: {st}; last verified {facility_network.last_verified_date}.", deduction)
    else:
        add("facility_network", "Facility network", "UNKNOWN", "The likely facility is not yet resolved in the available records.", 8)

    pa_rule = benefit.prior_authorization_rule if benefit else "CONDITIONAL"
    if pa_rule == "NOT_REQUIRED":
        add("authorization", "Prior authorization", "NOT_APPLICABLE", "The synthetic benefit configuration marks prior authorization as not required for this service group.")
    elif pa:
        mapping = {
            "APPROVED": "READY",
            "PENDING": "IN_PROGRESS",
            "MORE_INFORMATION_REQUIRED": "NEEDS_ATTENTION",
            "DENIED": "NEEDS_ATTENTION",
            "CANCELLED": "UNKNOWN",
        }
        status = mapping.get(pa.authorization_status, "UNKNOWN")
        deduction = 0 if status == "READY" else 10 if status == "IN_PROGRESS" else 25 if status == "NEEDS_ATTENTION" else 8
        add("authorization", "Prior authorization", status, f"Authorization status: {pa.authorization_status}.", deduction)
    else:
        add("authorization", "Prior authorization", "NEEDS_ATTENTION", "No matching authorization record was found for a service with a conditional authorization rule.", 25)

    referral_rule = benefit.referral_rule if benefit else "CONDITIONAL"
    add(
        "referral",
        "Referral",
        "NOT_APPLICABLE" if referral_rule == "NOT_REQUIRED" else "UNKNOWN",
        "Referral is not required by this synthetic benefit configuration."
        if referral_rule == "NOT_REQUIRED"
        else "Referral requirement is conditional and should be confirmed with the provider workflow.",
        0 if referral_rule == "NOT_REQUIRED" else 5,
    )

    if accumulator:
        add(
            "cost",
            "Member cost-share context",
            "READY",
            f"${accumulator.medical_deductible_remaining:,.0f} deductible and ${accumulator.in_network_oop_remaining:,.0f} in-network OOP remaining in the synthetic accumulator.",
        )
    else:
        add("cost", "Member cost-share context", "UNKNOWN", "Benefit accumulator is unavailable.", 10)

    # These are benefit availability checks only. Absence of a utilization/arrangement record is not treated as a problem.
    for group, key, label in [
        ("PHYSICAL_THERAPY", "pt", "Physical therapy benefit"),
        ("TRANSPORTATION", "transportation", "Transportation benefit"),
        ("DME", "dme", "DME benefit"),
        ("HOME_HEALTH", "home_health", "Home health benefit"),
    ]:
        b = db.query(models.PlanBenefit).filter(
            models.PlanBenefit.plan_id == member.plan_id,
            models.PlanBenefit.service_group == group,
        ).first()
        if not b:
            add(key, label, "UNKNOWN", "No matching benefit row is available.")
        elif b.coverage_status == "COVERED":
            add(key, label, "READY", f"Covered: {b.coverage_limit_or_note}; member cost share {b.in_network_member_cost_share}.")
        else:
            add(key, label, "NOT_APPLICABLE", "This benefit is not included in the synthetic plan configuration.")

    score = max(0, min(100, score))
    unresolved = [i for i in items if i.status in {"NEEDS_ATTENTION", "IN_PROGRESS", "UNKNOWN"}]
    deterministic_top = unresolved[0] if unresolved else None

    alternatives: list[ProviderAlternative] = []
    if any(i.key == "facility_network" and i.status == "NEEDS_ATTENTION" for i in items):
        alternatives = get_alternatives(db, member_id, "Hospital / Surgical Facility", provider_type="FACILITY")
    elif any(i.key == "surgeon_network" and i.status == "NEEDS_ATTENTION" for i in items):
        alternatives = get_alternatives(db, member_id, specialty, provider_type="PRACTITIONER")

    label = "Administratively ready" if score >= 85 else "Mostly ready" if score >= 70 else "Needs attention"
    baseline = ReadinessResult(
        member_id=member_id,
        predicted_care_event=event,
        readiness_score=score,
        readiness_label=label,
        checklist=items,
        top_issue=deterministic_top.label if deterministic_top else None,
        score_explanation=explanations,
        alternatives=alternatives,
        recommended_next_action="Continue monitoring and confirm final administrative details." if not deterministic_top else f"Resolve or verify {deterministic_top.label.lower()}.",
        generated_by="Deterministic readiness checks",
    )
    return baseline, specialty


async def analyze_readiness(db: Session, member_id: str, care: CareIntentResult) -> ReadinessResult:
    if settings.use_mock_ai:
        raise RuntimeError("Mock AI is disabled for this version. Configure OPENAI_API_KEY.")

    cache_key = (
        member_id,
        care.care_intent.predicted_care_event or "",
        care.care_intent.confidence,
        settings.openai_model,
    )
    if cache_key in READINESS_CACHE:
        result = READINESS_CACHE[cache_key]
        LATEST_READINESS_RESULTS[member_id] = result
        return result

    baseline, _ = _build_deterministic_readiness(db, member_id, care)
    packet = {
        "member_id": member_id,
        "predicted_care_event": baseline.predicted_care_event,
        "care_intent_confidence": care.care_intent.confidence,
        "readiness_score": baseline.readiness_score,
        "checklist": [item.model_dump() for item in baseline.checklist],
        "available_in_network_alternatives": [alt.model_dump() for alt in baseline.alternatives],
    }

    started = time.perf_counter()
    provider = OpenAIProvider()
    agent_output, usage = await provider.generate_json(system_prompt=READINESS_AGENT_PROMPT, user_payload=packet)

    valid_keys = {item.key: item for item in baseline.checklist}
    requested_key = agent_output.get("top_issue_key")
    if requested_key not in valid_keys or valid_keys[requested_key].status not in {"NEEDS_ATTENTION", "IN_PROGRESS", "UNKNOWN"}:
        unresolved = [item for item in baseline.checklist if item.status in {"NEEDS_ATTENTION", "IN_PROGRESS", "UNKNOWN"}]
        requested_key = unresolved[0].key if unresolved else None

    top_issue = valid_keys[requested_key].label if requested_key else None
    action = str(agent_output.get("recommended_next_action") or baseline.recommended_next_action).strip()
    if not action:
        action = baseline.recommended_next_action

    result = baseline.model_copy(update={
        "top_issue": top_issue,
        "recommended_next_action": action,
        "generated_by": f"OPENAI · {settings.openai_model} + deterministic checks",
    })

    latency = int((time.perf_counter() - started) * 1000)
    input_tokens = usage.get("input_tokens") or estimate_tokens(json.dumps(packet, default=str))
    output_tokens = usage.get("output_tokens") or estimate_tokens(json.dumps(agent_output))
    log_usage(
        db,
        agent_name="READINESS",
        member_id=member_id,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        latency_ms=latency,
        transcript_tool_invoked=False,
        mode=f"OPENAI:{settings.openai_model}",
    )

    READINESS_CACHE[cache_key] = result
    LATEST_READINESS_RESULTS[member_id] = result
    return result
